In [1]:
import numpy as x
arr=x.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [2]:
import numpy as x
arr=x.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as x
arr=x.zeros(6)
print(arr)

[0. 0. 0. 0. 0. 0.]


In [4]:
import numpy as x
arr=x.ones((3,2),dtype=int)
print(arr)

[[1 1]
 [1 1]
 [1 1]]


In [5]:
import numpy as x
arr=x.array([2,3,4],dtype=float)
print(arr,type(arr))

[2. 3. 4.] <class 'numpy.ndarray'>


In [6]:
import numpy as x
arr=x.empty((2,2))
print(arr)

[[2.12199579e-314 0.00000000e+000]
 [3.08296963e-321 6.95250701e-310]]


In [7]:
import numpy as x
x=x.arange(0,20,2)
print(x)

[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
import numpy as x
arr=x.linspace(0,1,6)
print(arr)

[0.  0.2 0.4 0.6 0.8 1. ]


In [9]:
x.random.random((3,3))

array([[0.80038665, 0.69478344, 0.8694478 ],
       [0.78976565, 0.09130428, 0.15787618],
       [0.82621381, 0.15134047, 0.11021125]])