In [1]:
import numpy as np
x = np.random.randint(1, 100, 10)
print("Original:", x)
y = np.sort(x)
print("np.sort():", y)
print("Original unchanged:", x)
x.sort()
print("x.sort():", x)

Original: [94 17 76  6 48 78 84 64 34 69]
np.sort(): [ 6 17 34 48 64 69 76 78 84 94]
Original unchanged: [94 17 76  6 48 78 84 64 34 69]
x.sort(): [ 6 17 34 48 64 69 76 78 84 94]


In [2]:
import numpy as np
x = np.random.randint(1, 100, 10)
i = np.argsort(x)
print("Original:", x)
print("x[i]:", x[i])
print("np.sort(x):", np.sort(x))

Original: [64 33  1 69  3 72 53 64 59 86]
x[i]: [ 1  3 33 53 59 64 64 69 72 86]
np.sort(x): [ 1  3 33 53 59 64 64 69 72 86]


In [3]:
import numpy as np
x = np.random.randint(1, 100, (4, 6))
print("Original:\n", x)
print("Row sorted:\n", np.sort(x, axis=1))
print("Column sorted:\n", np.sort(x, axis=0))

Original:
 [[ 9 20 31 10 98 42]
 [19 90 55 78 36 23]
 [35 82 82 33  7  6]
 [61  9 75  9 72 39]]
Row sorted:
 [[ 9 10 20 31 42 98]
 [19 23 36 55 78 90]
 [ 6  7 33 35 82 82]
 [ 9  9 39 61 72 75]]
Column sorted:
 [[ 9  9 31  9  7  6]
 [19 20 55 10 36 23]
 [35 82 75 33 72 39]
 [61 90 82 78 98 42]]


In [4]:
import numpy as np
x = np.random.randint(1, 100, 15)
p = np.partition(x, 4)
print("Original:", x)
print("4 smallest:", p[:4])
print("Verify:", np.sort(x)[:4])

Original: [52 69 57 80 82 13 70 46 56 54 65 69 14 78 95]
4 smallest: [13 46 14 52]
Verify: [13 14 46 52]


In [7]:
import numpy as np
student_names = np.array(["Rahul", "Anu", "Kiran", "Sneha", "Ravi"])
scores = np.array([75, 92, 68, 85, 78])
i = np.argsort(scores)
for j in i:
    print(student_names[j], scores[j])

Kiran 68
Rahul 75
Ravi 78
Sneha 85
Anu 92


In [8]:
import numpy as np
X = np.random.rand(10, 2)
dist_sq = np.sum(
    (X[:, np.newaxis, :] - X[np.newaxis, :, :]) ** 2,
    axis=-1
)
i = np.argsort(dist_sq, axis=1)
for j in range(10):
    print("Point", j, "->", i[j, 1:3])

Point 0 -> [8 3]
Point 1 -> [8 4]
Point 2 -> [5 6]
Point 3 -> [7 0]
Point 4 -> [6 5]
Point 5 -> [2 6]
Point 6 -> [5 2]
Point 7 -> [3 2]
Point 8 -> [0 1]
Point 9 -> [6 2]


In [1]:
import numpy as np
dtype = [('title', 'U30'), ('author', 'U20'), ('price', 'f4')]
books = np.array([
    ('Python Basics', 'John', 450.0),
    ('Data Science', 'Smith', 600.0),
    ('Machine Learning', 'David', 750.0),
    ('NumPy Guide', 'James', 500.0)
], dtype=dtype)
print(books)

[('Python Basics', 'John', 450.) ('Data Science', 'Smith', 600.)
 ('Machine Learning', 'David', 750.) ('NumPy Guide', 'James', 500.)]


In [2]:
print(books['title'])
print(books[1])
print(books[books['price'] < 600])

['Python Basics' 'Data Science' 'Machine Learning' 'NumPy Guide']
('Data Science', 'Smith', 600.)
[('Python Basics', 'John', 450.) ('NumPy Guide', 'James', 500.)]


In [3]:
dtype1 = {'names':['title','author','price'],
          'formats':['U30','U20','f4']}
dtype2 = [('title','U30'), ('author','U20'), ('price','f4')]
print(np.dtype(dtype1) == np.dtype(dtype2))

True


In [4]:
data_rec = books.view(np.recarray)
print(data_rec.price)

[450. 600. 750. 500.]


In [5]:
students = np.array([
    (1, 'Anu', 85),
    (2, 'Ravi', 92),
    (3, 'Kiran', 78),
    (4, 'Meena', 95),
    (5, 'Rahul', 88)
], dtype=[('roll_no','i4'), ('name','U20'), ('marks','f4')])
students = np.sort(students, order='marks')[::-1]
print(students)

[(4, 'Meena', 95.) (2, 'Ravi', 92.) (5, 'Rahul', 88.) (1, 'Anu', 85.)
 (3, 'Kiran', 78.)]
